# Generated by Django 5.0 on 2026-06-02 04:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(default='Sin ubicación', max_length=150, verbose_name='Ubicación')),
                ('capacidad_maxima', models.IntegerField()),
                ('precio_por_hora', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio_por_dia', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Mantenimiento', 'En Mantenimiento'), ('Inactiva', 'Inactiva')], default='Disponible', max_length=20)),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='salas_portadas/')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('tipo_renta', models.CharField(choices=[('Hora', 'Por Hora'), ('Dia', 'Por Día')], max_length=10)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_reserva', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.sala')),
            ],
        ),
    ]
