# Generated by Django 5.0 on 2026-06-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='tipo_plano',
            field=models.CharField(choices=[('oficina', 'Oficina / Sala de Juntas'), ('fiesta', 'Salón de Fiestas'), ('cine', 'Auditorio / Cine')], default='oficina', max_length=20, verbose_name='Tipo de Plano (Visual)'),
        ),
    ]
